version: '3.4'

services: 
  namingserver: 
    image: maven:3.8.4-jdk-11
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 700m 
    ports: 
      - "8000:8761" 
    network_mode: bridge